server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rn_ionic
    username: rnuser
    password: rnpass

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true