server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://192.168.100.162:5432/rn_ionic
    username: rnuser
    password: rnpass
  mail:
    host: 192.168.100.162
    port: 1025
    username:
    password:
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

  jpa:
    hibernate:
      ddl-auto: validate
      properties:
        hibernate:
          format_sql: true
app:
  jwt:
    secret: ${JWT_SECRET:8f4c2d91b7e64a3fa2c8d5e1f7a9b3c6eid8f1a5b7q9d2e6f3a8c1b4d7e9f2a2}
    issuer: "mobileapi"
    access-token-minutes: 60

  flyway:
    enabled: true
logging:
  level:
    org.hibernate.SQL: debug